#!/usr/bin/env ruby -W
$LOAD_PATH.push("lib")

require 'rate_parser'
require 'transaction_parser'
require 'solver'
require 'chain_builder'

rate_file = ARGV[0]
transaction_file = ARGV[1]

rates = RateParser.parse(rate_file)
transactions = TransactionParser.parse(transaction_file)

rate_chain = ChainBuilder.build(rates, "USD")

solver = Solver.new(transactions, "DM1182", rate_chain, "USD")
puts solver.solution.to_f

